### ISSUE TITLE
0.4.0 breaks my build

### ISSUE THREAD

**Issue by sumerman** [lau/calecto#13]
"Because of protocols, they can still be used with the Calendar functions for formatting, timezone shifting etc." this line from the changelog is simply not true.  Functions like `Calendar.DateTime.diff` are actually defined on data structures from `Calendar`.

Furthermore I actually have some of my protocols implemented for `Calendar`, now I have to duplicate this code for `Calecto` structures.

And just out of curiosity why you decided to change the underlaying data structures?

**Comment by lau** [comment]
Hi

> "Because of protocols, they can still be used with the Calendar functions for formatting, timezone shifting etc." this line from the changelog is simply not true.

It is true for most functions in Date, Strftime, NaiveDateTime, Time. But I guess Calendar.DateTime functions need to have some functions added, so that DateTimeUTC structs can be used with Calendar.DateTime functions. Thank you for bringing that to my attention. I assume that it is a `Calecto.DateTimeUTC` field that you want to use `Calendar.DateTime.diff` on?

I plan to fix the issue with DateTimeUTC compatability with Calendar.DateTime functions.

I decided to change it so that you can use them in queries. E.g. you can use Calecto.Date structs in an Ecto query.

**Comment by lau** [comment]
The only function I haven't found to work are `Calendar.DateTime.diff` (and related functions before? after? same_time?). Have you found any other functions that don't work?

**Comment by lau** [comment]
@sumerman Try upgrading Calendar to version 0.12.1 And also upgrading Calecto to the newest version.

Calendar.DateTime.diff should work with DateTime.diff now.

Let me know if you find any other problems.

**Comment by sumerman** [comment]
@lau Thanks for fixing diff. Sorry it took me so long, didn't have time for the project I'm using calecto in.
But I still have to implement my protocols twice, have `<=` operator broken.

**Comment by lau** [comment]
>  But I still have to implement my protocols twice, have <= operator broken.

Could you post a more detailed explanation of what you are trying to do? If you want you can cast e.g. Calendar.Date as Calecto.Date and the other way around.

**Comment by sumerman** [comment]
Let's say I just don't understand the reason to have 2 different datatypes with exactly the same structure given that you are the maintainer of both projects. Furthermore there are cases (even in your own `calendar_phoenix`) where you have to have protocol implemented kinda-twice (although I didn't know different modules can share the implementation). Finally, for terms representing dates erlang term order was a natural way to compare. 

You obviously won't rollback your changes, and I don't mind fixing my project, but at least I want to know the why.

**Comment by lau** [comment]
I explained why:

> I decided to change it so that you can use them in queries. E.g. you can use Calecto.Date structs in an Ecto query.

To expand: At the time you could not do queries using e.g. Calendar.Date or Calendar.DateTime because of how Ecto treated custom types.

Fortunately Ecto has since added the Ecto.DataType protocol. This allows getting rid of the Calecto structs so Calendar structs can be used in queries too. So I plan to implement that protocol and get rid of the Calecto structs. So there won't be two different datatypes representing the same thing anymore.

**Comment by sumerman** [comment]
@lau thanks, after expanded explanation it all makes sense.

**Comment by lau** [comment]
You're welcome. Version 0.5.0 has been released and goes back to returning Calendar structs instead of Calecto structs.

**Comment by sumerman** [comment]
@lau thank you again.
