### ISSUE TITLE
Kalecto.Model macro usage

### ISSUE THREAD

**Issue by djm** [lau/calecto#2]
Hi,

First off, thanks very much for your work on these datetime packages. Super, super useful.

I'm still relatively new to Elixir but I am confused by the instructions in the README:

> In your Ecto models, where you have a schema definition with a timestamps line, add `use Kalecto.Model` at the top of the module, **below the line that says `use Ecto.Model`**

When using both `use` lines in an Ecto model definition, compilation seems to raise this warning:

> model.ex:1: warning: this clause cannot match because a previous clause at line 1 always matches

...and looking at the [macro code](https://github.com/lau/kalecto/blob/f8f8f0d835520c72210ac13a1739cf6c73fe0d73/lib/kalecto/model.ex#L5) itself, it seems to declare `use Ecto.Model` for you.

So I guess the question is, am I missing a reason for asking users to specify both lines?

cheers,
Darian

**Comment by lau** [comment]
Hi Darian. I'm glad you find it useful.

You are right, it should work if you only use this line: `use Kalecto.Model`

As far as I remember I thought it would be less confusing with both lines. But I guess it isn't. And it's redundant. So the answer is that there is no good reason that the readme says that :) I'll fix it.

Thanks for the feedback. The documentation for Kalecto is lacking because the other packages (kalends and tzdata) have had a higher priority, but eventually it should improve.

**Comment by djm** [comment]
Awesome, thanks for clearing that up.

**Comment by lau** [comment]
@djm FYI for the newest version (0.3.1) I have gone back to having both lines (use Ecto.Model and use Kalecto.Model). The line that caused the compilation error was redundant as is no longer there.

I think it makes more sense this way with both lines

**Comment by djm** [comment]
@lau cool, thanks for the headsup.
