### ISSUE TITLE
Loading / Encoding issues.

### ISSUE THREAD

**Issue by benwilson512** [lau/calecto#38]
Hey @lau, I'm trying to use the Calecto.DateTime type and getting the following error when writing a value:

```
** (ArgumentError) could not encode date/time: {{{2018, 8, 9}, {12, 56, 42, 0}}, -14400, "EST5EDT"}

This error happens when you are by-passing Ecto's Query API by
using either Ecto.Adapters.SQL.query/4 or Ecto fragments. This
makes Ecto unable to properly cast the type. You can fix this by
explicitly telling Ecto which type to use via `type/2` or by
implementing the Ecto.DataType protocol for the given value.

    (ecto) lib/ecto/adapters/postgres/datetime.ex:88: Ecto.Adapters.Postgres.Timestamp.encode!/1
    (sensetra) lib/ecto/adapters/postgres/datetime.ex:126: Sensetra.PostgresTypes.encode_params/3
    (postgrex) lib/postgrex/query.ex:45: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection) lib/db_connection.ex:1079: DBConnection.describe_run/5
    (db_connection) lib/db_connection.ex:1150: anonymous fn/4 in DBConnection.run_meter/5
    (db_connection) lib/db_connection.ex:592: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:86: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
```

A similar error happens if I try to load a value

Versions:

Elixir 1.7.2
Ecto 2.2.10
Calecto 0.17.0

**Comment by lau** [comment]
Hi @benwilson512 

Is that when inserting?

What type do you have in your migration for the field where the type is `Calecto.DateTime` in the schema? This one should work for the migration: `:calendar_datetime`.

It requires a migration to be run as described in https://github.com/lau/calecto#datetime-with-postgres that adds the `calendar_datetime` type to the postgres database.

I can insert using 
:calecto, "0.17.0", :ecto, "2.2.10", Elixir 1.7.2

**Comment by benwilson512** [comment]
Hey @lau this is indeed when inserting. The migration I used `:timestampz` which produced a `TIMESTAMP WITH TIMEZONE` column type if I look at the table in postgresql.

From your link I'm realizing that this is maybe not what Calect.DateTime expects, does it use a custom database column type?

**Comment by lau** [comment]
@benwilson512 Yes, `Calecto.DateTime` requires a custom database column type. See https://github.com/lau/calecto#the-types 
and https://github.com/lau/calecto#datetime-with-postgres

Postgres' "TIMESTAMP WITH TIMEZONE" is not a well named type. One might think that it saves the timezone. It does not. Whatever you save is converted to UTC and saved in UTC. When you read it back from postgres postgres has no idea what timezone it was because the timezone was not saved. So I do not think it is appropriate if you want to have the timezone saved. If all you want to save is UTC DateTimes I would recommend using Ecto's `:utc_datetime` in the Ecto schema. I think this works with columns created in postgres as timestampz as well. If you use :timestampz I would recommend making sure that the database server and the servers talking to the database always have their time zone set to UTC.

If you want to save datetimes with timezones that are not solely UTC you can use Calecto's custom type. It is a composite type. For Ecto 2.1+ and Elixir 1.3+ this type is the main reason to still use Calecto since Ecto now has a built in equivalent for all of the others.  Alternatively you could use two simple fields: a :naive_datetime plus a string with the timezone id e.g. "America/New_York" but then you would have to do some more work yourself when inserting and retrieving them as `DateTime`s.
